[package]
name = "libtrig-llm"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies.macros]
package = "libtrig-macros"
path = "../macros"

[features]
default = ["unstable"]
unstable = []
