[workspace]
resolver = "2"
members = [
    # Main crates
    "arc", # Client side of the robot (python)
    "libs/robot", # Robot [Server] side of the robot (rust)

    # Helper crates
    "libs/helper/l2math",
    # "libs/libodo",
    # "libs/libpath",
    # "libs/libtrig",
    "libs/helper/macros-core",
    "libs/helper/macros",
]

[workspace.package]
authors = ["Матвей Т <https://matveit.dev> AtomicGamer9523@github"]
repository = "https://github.com/DranikiRobotics/arc"
version = "0.0.1-dev"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 3
# debug = false
debug = true
# panic = "abort"
panic = "unwind"
