[workspace]
members = [
    "core/llm",
    "core/macros"
]

[package]
name = "libtrig"
version = "0.1.0"
edition = "2021"

[dependencies.macros]
package = "libtrig-macros"
path = "./core/macros"

[dependencies.llm]
package = "libtrig-llm"
path = "./core/llm"

[lib]
path = "./libtrig/lib.rs"
