[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
doctest = false

[dependencies.macros]
path = "../utils/macros"

[features]
default = ["unstable"]
unstable = []
