[package]
name = "libtrig-macros-core"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
