[package]
name = "arc-uploader"
description = "ARC Robot Code Uploader"
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "arc-uploader"
path = "main.rs"
